const middlewareAuth = require('../../middlewares/auth')
const adminUserRouter = require('./adminUser')
const taskRouter = require('./task')
const circleUserRouter = require('./circleUser')
const noteRouter = require('./note')
const topicRouter = require('./topic')
const messageRouter = require('./message')
const commentRouter = require('./comment')
const friendRouter = require('./friend')
const rateRouter = require('./rate')
const scoreRouter = require('./score')

const webRouter = app => {
  app.use('/api/web/admin_users', adminUserRouter)
  app.use('/api/web/tasks', middlewareAuth(), taskRouter)
  app.use('/api/web/circle_users', middlewareAuth(), circleUserRouter)
  app.use('/api/web/notes', middlewareAuth(), noteRouter)
  app.use('/api/web/topics', middlewareAuth(), topicRouter)
  app.use('/api/web/messages', middlewareAuth(), messageRouter)
  app.use('/api/web/comments', middlewareAuth(), commentRouter)
  app.use('/api/web/friends', middlewareAuth(), friendRouter)
  app.use('/api/web/rates', middlewareAuth(), rateRouter)
  app.use('/api/web/scores', middlewareAuth(), scoreRouter)
}
module.exports = webRouter